name: Product Catalog - CI
on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
    workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }} 
    
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            version: [1.25]
        defaults:
          run:
            working-directory: src/productcatalogservice
        steps:
            - name: checkout
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
            - name: Setup Go
              uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4
              with:
                go-version: ${{ matrix.version }}
                cache-dependency-path: 'src/productcatalogservice/go.sum'
            - name: Install dependencies
              run: go mod download

            - name: Build application
              run: go build

            - name: Run Tests
              run: go test -v -race
    golangci:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
          - name: Setup Go
            uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4
            with:
                go-version-file: 'src/productcatalogservice/go.mod'
                cache-dependency-path: 'src/productcatalogservice/go.sum'
          - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0 
            with:
                working-directory: src/productcatalogservice
            continue-on-error: true #Temporariamente até corrigir os erros do linter
    docker_build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
          - name: Build Docker Image
            run: docker build -t product-catalog-service:latest -f src/productcatalogservice/Dockerfile .
          
            


